

#define TestIdling /* C_0 - TestIdling */ 100
 
enum EN0 {
	SCM2VP_INSERT_HANDS /* SCM2VP_INSERT_HANDS */,
	SCM2VP_TAKE_AWAY_HANDS /* SCM2VP_TAKE_AWAY_HANDS */

};
 
enum EN1 {
	SCM2VM_FINISH_VERIFICATION /* SCM2VM_FINISH_VERIFICATION */

};

enum EN2 {
	VM2SCM_START_VERIFICATION /* VM2SCM_START_VERIFICATION */

};